"""
Django settings for pathcare project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*pdc3b0r#!6aivu7wb3bln57=13-)=4(+v&3mr7g&fa^0s5009'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.getenv("DEBUG", "False") == "True"

allowed_hosts_env = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,.ngrok-free.dev,.ngrok.app,.onrender.com,pathcare-tracking.onrender.com"
)
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]

render_host = os.environ.get("RENDER_EXTERNAL_URL", "")
if render_host:
    parsed_render_host = urlparse(render_host).netloc or urlparse(render_host).path
    if parsed_render_host:
        ALLOWED_HOSTS.append(parsed_render_host)

# Needed when accessing the app through an ngrok tunnel (or any reverse proxy) -
# Django checks the request's Origin header against this list for CSRF safety.
# The wildcard covers ngrok's random subdomain, which changes each time you
# restart a free-tier tunnel.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    "https://pathcare-tracking.onrender.com",
    "https://*.ngrok-free.dev",
    "https://*.ngrok.app",
    "https://*.onrender.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

if render_host:
    CSRF_TRUSTED_ORIGINS.append(render_host)
# Application definition

INSTALLED_APPS = [
    'daphne',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    # Local
    'accounts',
    'clients',
    'carriers',
    'orders',
    'samples',
    'custody',
    'dispatch',
    'tracking',
    'notifications',
    'reports',
    'dashboard',
    'core',
]

# Static files via whitenoise
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# PWA Security Headers
SECURE_SSL_REDIRECT = False
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
        "script-src": ("'self'", "'unsafe-inline'", "unpkg.com"),
        "style-src": ("'self'", "'unsafe-inline'", "unpkg.com"),
        "img-src": ("'self'", "data:", "https:"),
        "font-src": ("'self'",),
        # "connect-src": ("'self'",),
        "connect-src": ("'self'", "ws:", "wss:"),
        "frame-ancestors": ("'none'",),
    }

ROOT_URLCONF = 'pathcare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tracking.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'pathcare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Uses SQLite locally by default, or DATABASE_URL when provided by the environment (e.g. Render)

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Ensure static files are served with correct content types for PWA
if not DEBUG:
    # For production
    STATICFILES_DIRS = [BASE_DIR / 'static']

# Fixed laboratory coordinates used for distance and ETA calculations.
LAB_LOCATION = {
    'latitude': -1.2921,
    'longitude': 36.8219,
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@pathcare.local')
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.locmem.EmailBackend')

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'accounts:role_redirect'
LOGOUT_REDIRECT_URL = 'login'

ASGI_APPLICATION = 'pathcare.asgi.application'

REDIS_URL = os.environ.get('REDIS_URL')
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
    SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": ("'self'",),
    "script-src": ("'self'", "'unsafe-inline'", "unpkg.com"),
    "style-src": ("'self'", "'unsafe-inline'", "unpkg.com"),
    "img-src": ("'self'", "data:", "https:"),
    "font-src": ("'self'",),
    "connect-src": ("'self'", "ws:", "wss:"),   # ← add ws: and wss:
    "frame-ancestors": ("'none'",),
}


ASGI_APPLICATION = 'pathcare.asgi.application'