# Generated by Django 5.2.16 on 2026-07-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_radius_km', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignment', to='tracking.carrier')),
            ],
        ),
    ]
