# Generated by Django 5.2.16 on 2026-07-24 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32)),
                ('vehicle_type', models.CharField(blank=True, max_length=64)),
                ('vehicle_plate', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_job', 'On job'), ('offline', 'Offline')], default='available', max_length=16)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(max_length=32, unique=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (immediate)')], default='routine', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending assignment'), ('assigned', 'Assigned to carrier'), ('accepted', 'Accepted by carrier'), ('en_route_client', 'En route to client'), ('at_client', 'Arrived at client'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered to lab'), ('received', 'Received at lab'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('requested_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tracking.carrier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tracking.client')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tracking.order')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('tissue', 'Tissue'), ('swab', 'Swab'), ('other', 'Other')], max_length=16)),
                ('cold_chain_requirement', models.CharField(choices=[('none', 'No special handling'), ('refrigerated', 'Refrigerated (2-8C)'), ('frozen', 'Frozen')], default='none', max_length=16)),
                ('is_damaged', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='tracking.order')),
            ],
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('order_created', 'Order created'), ('carrier_assigned', 'Carrier assigned'), ('assignment_accepted', 'Assignment accepted'), ('started_to_client', 'Started trip to client'), ('arrived_at_client', 'Arrived at client'), ('picked_up', 'Picked up from client'), ('temp_check', 'Temperature check'), ('departed', 'Departed (in transit)'), ('delivered', 'Delivered to lab'), ('received', 'Received at lab'), ('completed', 'Order completed'), ('exception', 'Exception (delay, damage, etc.)')], max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='custody_photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='tracking.order')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='tracking.sample')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
