# Generated by Django 5.2.16 on 2026-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_order_pickup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Priority'), ('stat', 'STAT (immediate)')], default='routine', max_length=16),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cold_chain_requirement',
            field=models.CharField(choices=[('ambient', 'Ambient'), ('refrigerated', '2–8°C (Refrigerated)'), ('frozen', 'Frozen'), ('dry_ice', 'Dry Ice'), ('liquid_nitrogen', 'Liquid Nitrogen')], default='ambient', max_length=16),
        ),
    ]
