# Generated by Django 5.2.16 on 2026-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_order_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order created'), ('request_approved', 'Request approved'), ('carrier_assigned', 'Carrier assigned'), ('assignment_accepted', 'Assignment accepted'), ('started_to_client', 'Started trip to client'), ('arrived_at_client', 'Arrived at client'), ('picked_up', 'Picked up from client'), ('temp_check', 'Temperature check'), ('departed', 'Departed (in transit)'), ('delivered', 'Delivered to lab'), ('received', 'Received at lab'), ('completed', 'Order completed'), ('exception', 'Exception (delay, damage, etc.)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('pending', 'Pending assignment'), ('assigned', 'Assigned to carrier'), ('accepted', 'Accepted by carrier'), ('en_route_client', 'En route to client'), ('at_client', 'Arrived at client'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered to lab'), ('received', 'Received at lab'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
