# Generated by Django 5.2.16 on 2026-07-27 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_custodyevent_event_type_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('accident', 'Accident'), ('puncture', 'Puncture'), ('delay', 'Delay'), ('vehicle', 'Vehicle issue'), ('other', 'Other')], default='other', max_length=24)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('resolved', 'Resolved')], default='reported', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tracking.carrier')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='tracking.order')),
            ],
        ),
    ]
