# Generated by Django 5.2.16 on 2026-07-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facility'),
        ('tracking', '0007_carrierissuereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_facility',
            field=models.ForeignKey(blank=True, help_text="Default facility for this client's pickups", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.facility'),
        ),
        migrations.AddField(
            model_name='order',
            name='facility',
            field=models.ForeignKey(blank=True, help_text="Facility for this pickup (defaults to client's default facility)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.facility'),
        ),
    ]
